/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20 from "./ERC20";
export type { erc20 };
import type * as data from "./data";
export type { data };
import type * as security from "./security";
export type { security };
export type { ThanksPay } from "./ThanksPay";
