/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface LMRevertReasonsInterface extends utils.Interface {
  functions: {
    "getReason(uint256)": FunctionFragment;
    "nReason()": FunctionFragment;
    "reasons(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getReason" | "nReason" | "reasons"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getReason",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nReason", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reasons",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getReason", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nReason", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reasons", data: BytesLike): Result;

  events: {};
}

export interface LMRevertReasons extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LMRevertReasonsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getReason(id: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    nReason(overrides?: CallOverrides): Promise<[BigNumber]>;

    reasons(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;
  };

  getReason(id: BigNumberish, overrides?: CallOverrides): Promise<string>;

  nReason(overrides?: CallOverrides): Promise<BigNumber>;

  reasons(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getReason(id: BigNumberish, overrides?: CallOverrides): Promise<string>;

    nReason(overrides?: CallOverrides): Promise<BigNumber>;

    reasons(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getReason(id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    nReason(overrides?: CallOverrides): Promise<BigNumber>;

    reasons(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getReason(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nReason(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reasons(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
