/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PartnerWon__factory } from "./PartnerWon__factory";
export { WorkerWon__factory } from "./WorkerWon__factory";
