/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as thanksRelaySol from "./thanksRelay.sol";
export { ThanksPayData__factory } from "./ThanksPayData__factory";
export { ReadData__factory } from "./ReadData__factory";
