/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as thanksRelaySol from "./ThanksRelay.sol";
export { ThanksData__factory } from "./ThanksData__factory";
export { ThanksDataStatic__factory } from "./ThanksDataStatic__factory";
