/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ThanksData__factory } from "./ThanksData__factory";
export { ThanksDataStatic__factory } from "./ThanksDataStatic__factory";
export { ThanksPayRelay__factory } from "./ThanksPayRelay__factory";
