/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as thanksRelaySol from "./thanksRelay.sol";
export type { thanksRelaySol };
export type { ThanksPayData } from "./ThanksPayData";
export type { ReadData } from "./ReadData";
