/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ThanksData } from "./ThanksData";
export type { ThanksDataStatic } from "./ThanksDataStatic";
export type { ThanksPayRelay } from "./ThanksPayRelay";
