/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as thanksRelaySol from "./ThanksRelay.sol";
export type { thanksRelaySol };
export type { ThanksData } from "./ThanksData";
export type { ThanksDataStatic } from "./ThanksDataStatic";
