/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ThanksPayDataInterface extends utils.Interface {
  functions: {
    "companyPools(address)": FunctionFragment;
    "partners(address)": FunctionFragment;
    "registerPartner(address,uint256,uint256)": FunctionFragment;
    "registerWorker(address,address,uint256)": FunctionFragment;
    "setLatestRequest(address,uint256)": FunctionFragment;
    "setPartnerBalance(address,uint256)": FunctionFragment;
    "setRelativePayday(address,uint256)": FunctionFragment;
    "setWorkerBalance(address,uint256)": FunctionFragment;
    "types(address)": FunctionFragment;
    "workers(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "companyPools"
      | "partners"
      | "registerPartner"
      | "registerWorker"
      | "setLatestRequest"
      | "setPartnerBalance"
      | "setRelativePayday"
      | "setWorkerBalance"
      | "types"
      | "workers"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "companyPools",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "partners",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPartner",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerWorker",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setLatestRequest",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPartnerBalance",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelativePayday",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setWorkerBalance",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "types",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "workers",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "companyPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "partners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerPartner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerWorker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLatestRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPartnerBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRelativePayday",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWorkerBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "types", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "workers", data: BytesLike): Result;

  events: {
    "companyPoolRegistered(address,uint256)": EventFragment;
    "partnerBalanceChanged(address,uint256)": EventFragment;
    "partnerRegistered(address,uint256)": EventFragment;
    "workerBalanceChanged(uint256,uint256)": EventFragment;
    "workerRegistered(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "companyPoolRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "partnerBalanceChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "partnerRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "workerBalanceChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "workerRegistered"): EventFragment;
}

export interface companyPoolRegisteredEventObject {
  pId: string;
  relativePayday: BigNumber;
}
export type companyPoolRegisteredEvent = TypedEvent<
  [string, BigNumber],
  companyPoolRegisteredEventObject
>;

export type companyPoolRegisteredEventFilter =
  TypedEventFilter<companyPoolRegisteredEvent>;

export interface partnerBalanceChangedEventObject {
  pId: string;
  newBalance: BigNumber;
}
export type partnerBalanceChangedEvent = TypedEvent<
  [string, BigNumber],
  partnerBalanceChangedEventObject
>;

export type partnerBalanceChangedEventFilter =
  TypedEventFilter<partnerBalanceChangedEvent>;

export interface partnerRegisteredEventObject {
  pId: string;
  relativePayday: BigNumber;
}
export type partnerRegisteredEvent = TypedEvent<
  [string, BigNumber],
  partnerRegisteredEventObject
>;

export type partnerRegisteredEventFilter =
  TypedEventFilter<partnerRegisteredEvent>;

export interface workerBalanceChangedEventObject {
  wId: BigNumber;
  newBalance: BigNumber;
}
export type workerBalanceChangedEvent = TypedEvent<
  [BigNumber, BigNumber],
  workerBalanceChangedEventObject
>;

export type workerBalanceChangedEventFilter =
  TypedEventFilter<workerBalanceChangedEvent>;

export interface workerRegisteredEventObject {
  wId: string;
  pId: string;
  wage: BigNumber;
}
export type workerRegisteredEvent = TypedEvent<
  [string, string, BigNumber],
  workerRegisteredEventObject
>;

export type workerRegisteredEventFilter =
  TypedEventFilter<workerRegisteredEvent>;

export interface ThanksPayData extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ThanksPayDataInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    companyPools(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { balance: BigNumber }>;

    partners(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        balance: BigNumber;
        relativePayday: BigNumber;
        latestPay: BigNumber;
      }
    >;

    registerPartner(
      pId: PromiseOrValue<string>,
      relativePayday: PromiseOrValue<BigNumberish>,
      latestPay: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerWorker(
      wId: PromiseOrValue<string>,
      pId: PromiseOrValue<string>,
      wage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLatestRequest(
      wId: PromiseOrValue<string>,
      latestRequest: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPartnerBalance(
      pId: PromiseOrValue<string>,
      newBalance: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRelativePayday(
      pId: PromiseOrValue<string>,
      relativePayday: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setWorkerBalance(
      wId: PromiseOrValue<string>,
      newBalance: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    types(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    workers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string, BigNumber] & {
        balance: BigNumber;
        wage: BigNumber;
        pId: string;
        latestRequest: BigNumber;
      }
    >;
  };

  companyPools(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  partners(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      balance: BigNumber;
      relativePayday: BigNumber;
      latestPay: BigNumber;
    }
  >;

  registerPartner(
    pId: PromiseOrValue<string>,
    relativePayday: PromiseOrValue<BigNumberish>,
    latestPay: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerWorker(
    wId: PromiseOrValue<string>,
    pId: PromiseOrValue<string>,
    wage: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLatestRequest(
    wId: PromiseOrValue<string>,
    latestRequest: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPartnerBalance(
    pId: PromiseOrValue<string>,
    newBalance: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRelativePayday(
    pId: PromiseOrValue<string>,
    relativePayday: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setWorkerBalance(
    wId: PromiseOrValue<string>,
    newBalance: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  types(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  workers(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, string, BigNumber] & {
      balance: BigNumber;
      wage: BigNumber;
      pId: string;
      latestRequest: BigNumber;
    }
  >;

  callStatic: {
    companyPools(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    partners(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        balance: BigNumber;
        relativePayday: BigNumber;
        latestPay: BigNumber;
      }
    >;

    registerPartner(
      pId: PromiseOrValue<string>,
      relativePayday: PromiseOrValue<BigNumberish>,
      latestPay: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerWorker(
      wId: PromiseOrValue<string>,
      pId: PromiseOrValue<string>,
      wage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLatestRequest(
      wId: PromiseOrValue<string>,
      latestRequest: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPartnerBalance(
      pId: PromiseOrValue<string>,
      newBalance: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRelativePayday(
      pId: PromiseOrValue<string>,
      relativePayday: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setWorkerBalance(
      wId: PromiseOrValue<string>,
      newBalance: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    types(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    workers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string, BigNumber] & {
        balance: BigNumber;
        wage: BigNumber;
        pId: string;
        latestRequest: BigNumber;
      }
    >;
  };

  filters: {
    "companyPoolRegistered(address,uint256)"(
      pId?: null,
      relativePayday?: null
    ): companyPoolRegisteredEventFilter;
    companyPoolRegistered(
      pId?: null,
      relativePayday?: null
    ): companyPoolRegisteredEventFilter;

    "partnerBalanceChanged(address,uint256)"(
      pId?: null,
      newBalance?: null
    ): partnerBalanceChangedEventFilter;
    partnerBalanceChanged(
      pId?: null,
      newBalance?: null
    ): partnerBalanceChangedEventFilter;

    "partnerRegistered(address,uint256)"(
      pId?: null,
      relativePayday?: null
    ): partnerRegisteredEventFilter;
    partnerRegistered(
      pId?: null,
      relativePayday?: null
    ): partnerRegisteredEventFilter;

    "workerBalanceChanged(uint256,uint256)"(
      wId?: null,
      newBalance?: null
    ): workerBalanceChangedEventFilter;
    workerBalanceChanged(
      wId?: null,
      newBalance?: null
    ): workerBalanceChangedEventFilter;

    "workerRegistered(address,address,uint256)"(
      wId?: null,
      pId?: null,
      wage?: null
    ): workerRegisteredEventFilter;
    workerRegistered(
      wId?: null,
      pId?: null,
      wage?: null
    ): workerRegisteredEventFilter;
  };

  estimateGas: {
    companyPools(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    partners(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerPartner(
      pId: PromiseOrValue<string>,
      relativePayday: PromiseOrValue<BigNumberish>,
      latestPay: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerWorker(
      wId: PromiseOrValue<string>,
      pId: PromiseOrValue<string>,
      wage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLatestRequest(
      wId: PromiseOrValue<string>,
      latestRequest: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPartnerBalance(
      pId: PromiseOrValue<string>,
      newBalance: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRelativePayday(
      pId: PromiseOrValue<string>,
      relativePayday: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setWorkerBalance(
      wId: PromiseOrValue<string>,
      newBalance: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    types(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    workers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    companyPools(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    partners(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerPartner(
      pId: PromiseOrValue<string>,
      relativePayday: PromiseOrValue<BigNumberish>,
      latestPay: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerWorker(
      wId: PromiseOrValue<string>,
      pId: PromiseOrValue<string>,
      wage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLatestRequest(
      wId: PromiseOrValue<string>,
      latestRequest: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPartnerBalance(
      pId: PromiseOrValue<string>,
      newBalance: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRelativePayday(
      pId: PromiseOrValue<string>,
      relativePayday: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setWorkerBalance(
      wId: PromiseOrValue<string>,
      newBalance: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    types(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    workers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
