/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as data from "./data";
export * as security from "./security";
export { ThanksPay__factory } from "./ThanksPay__factory";
