/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "ThanksPayCheck",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThanksPayCheck__factory>;
    getContractFactory(
      name: "ThanksData",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThanksData__factory>;
    getContractFactory(
      name: "ThanksDataStatic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThanksDataStatic__factory>;
    getContractFactory(
      name: "ThanksPayRelay",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThanksPayRelay__factory>;
    getContractFactory(
      name: "RevertCheck",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RevertCheck__factory>;
    getContractFactory(
      name: "ThanksSecurity",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThanksSecurity__factory>;
    getContractFactory(
      name: "ThanksSecurityWrapper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThanksSecurityWrapper__factory>;
    getContractFactory(
      name: "ThanksPayMain",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ThanksPayMain__factory>;

    getContractAt(
      name: "AccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "IAccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "ThanksPayCheck",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThanksPayCheck>;
    getContractAt(
      name: "ThanksData",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThanksData>;
    getContractAt(
      name: "ThanksDataStatic",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThanksDataStatic>;
    getContractAt(
      name: "ThanksPayRelay",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThanksPayRelay>;
    getContractAt(
      name: "RevertCheck",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.RevertCheck>;
    getContractAt(
      name: "ThanksSecurity",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThanksSecurity>;
    getContractAt(
      name: "ThanksSecurityWrapper",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThanksSecurityWrapper>;
    getContractAt(
      name: "ThanksPayMain",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ThanksPayMain>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
